apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  labels:
    app: nextcloud
data:
  NEXTCLOUD_UPDATE: "1"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_DB: "nextcloud"
  NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1 localhost nextcloud nextcloud.default.svc nextcloud.default.svc.cluster.local"